platform :ios, '8.0'
use_frameworks!

target 'CartoonOnlie' do
  pod ‘SDWebImage’, '~> 3.8.1’
  pod 'SDCycleScrollView', '~> 1.65'
  pod 'SDWebImage/WebP'
  pod 'UMengSocialCOM', '~> 5.2.1'
  pod 'MJRefresh', '~> 3.1.10'
end
