platform :ios, '8.0'
use_frameworks!

target 'CartoonOnlie' do
  pod "Masonry"
  pod 'SDWebImage', '~> 3.8.1’
  pod 'SDCycleScrollView', '~> 1.65'
  pod 'SDWebImage/WebP'
  pod 'UMengSocialCOM', '~> 5.2.1'
  pod 'MJRefresh', '~> 3.1.10'
  pod 'FMDB', '~> 2.6.2’
  pod 'SDAutoLayout', '~> 2.1.3'
  pod 'MBProgressHUD', '~> 0.9.2'
  pod 'RealReachability', '~> 1.1.7'
  pod "DBSphereTagCloud"
  pod "MPFoldTransition"
  pod "SlimeRefresh"
  pod "AnimatedGIFImageSerialization"
  pod "AFNetworking", "~>2.0"
  pod "FXBlurView"
end
